version: '3.1'
services:
 rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - '/data/docker_data/rabbitmq:/data'

volumes:
  rabbitmq_data: