version: '3.1'
# Docker Compose excerpt
services:
  nginx-ui:
    image: schenkd/nginx-ui:latest
    restart: always
    ports:
      - 127.0.0.1:8087:8080
    volumes:
      - /etc/nginx:/etc/nginx

volumes:
  nginx_data: