# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - /Users/jay/DockerData/mysql:/var/lib/mysql 
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root


  adminer:
    image: adminer
    container_name: mysql_adminer
    restart: always
    ports:
      - 8080:8080